force-app/main/default/objects/Contact/fields/Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Picture_URL__c</fullName>
    <description>Url of a photo/picture to use in Coneference Session list.</description>
    <label>Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Date_and_Time__c.field-meta.xml
<CustomField>
    <fullName>Date_and_Time__c</fullName>
    <label>Date and Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Room__c.field-meta.xml
<CustomField>
    <fullName>Room__c</fullName>
    <label>Room</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Keynote room</fullName>
            </value>
            <value>
                <fullName>Theater</fullName>
            </value>
            <value>
                <fullName>Breakout room A</fullName>
            </value>
            <value>
                <fullName>Breakout room B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/Session_Speaker__c.object-meta.xml
<CustomObject>
    <description>A junction object to represent many-to-many relationship between Session and Contact.</description>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SESP-{00000}</displayFormat>
        <label>Session Speaker Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session_Speaker__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <description>A certain session where speaker is performing.</description>
    <label>Session</label>
    <referenceTo>Session__c</referenceTo>
    <relationshipLabel>Speakers</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <description>A person who will be a speaker or a certain session.</description>
    <label>Speaker</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Sessions</relationshipLabel>
    <relationshipName>Session_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SessionController.cls
public with sharing class SessionController {
    @AuraEnabled(cacheable=true)
    public static List<Session__c> getSessions(String searchKey) {
        if (String.isBlank(searchKey)) {
            return [SELECT Id, Name, toLabel(Room__c), Description__c, format(Date_and_Time__c) dateTime,
                    (SELECT Speaker__r.Id, Speaker__r.Name, Speaker__r.Description, Speaker__r.Email, Speaker__r.Picture_URL__c FROM Session_Speakers__r)
                    FROM Session__c ORDER BY Date_and_Time__c LIMIT 100];
        } else {
            String key = '%' + searchKey + '%';
            return [SELECT Id, Name, toLabel(Room__c), Description__c, format(Date_and_Time__c) dateTime,
                    (SELECT Speaker__r.Id, Speaker__r.Name, Speaker__r.Description, Speaker__r.Email, Speaker__r.Picture_URL__c FROM Session_Speakers__r)
                    FROM Session__c WHERE Name LIKE :key ORDER BY Date_and_Time__c LIMIT 100];
        }
    }
    
    @AuraEnabled(cacheable=true)
    public static Session__c getSession(Id sessionId) {
        List<Session__c> sessions = [SELECT Id, Name, toLabel(Room__c), Description__c, format(Date_and_Time__c) dateTime,
                                     (SELECT Speaker__r.Id, Speaker__r.Name, Speaker__r.Description, Speaker__r.Email, Speaker__r.Picture_URL__c FROM Session_Speakers__r)
                                     FROM Session__c WHERE Id = :sessionId];
        if (sessions.size() < 1) {
            throw new AuraHandledException('Could not find session');
        }
        return sessions[0];
    }
    
    @AuraEnabled
    public static Id addSession(String sessionName, String sessionLocation, String sessionDescription, DateTime sessionTime, List<Id> sessionSpeakerId) {
        try{
            Session__c newSession = new Session__c(Name = sessionName, Room__c = sessionLocation, Description__c = sessionDescription, Date_and_Time__c = sessionTime);
            insert newSession;
            List<Session_Speaker__c> speakerList = new List<Session_Speaker__c>();
            Set<Id> sessionSpeakerIdSet = new Set<Id>(sessionSpeakerId);
            for(Id speakerId: sessionSpeakerIdSet){
                speakerList.add(new Session_Speaker__c(Speaker__c = speakerId, Session__c = newSession.Id));
            }
            insert speakerList;
            return newSession.Id;
        }
        catch(Exception e){ throw new AuraHandledException('Session was not created: ' + e.getMessage()); }
    }
    
    @AuraEnabled(cacheable=true)
    public static List<String> getLocationPickListValuesIntoList(){
        try{
            List<String> pickListValuesList= new List<String>();
            Schema.DescribeFieldResult fieldResult = Session__c.Room__c.getDescribe();
            List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
            for(Schema.PicklistEntry pickListVal : ple){
                pickListValuesList.add(pickListVal.getLabel());
            }
            return pickListValuesList;
        }
        catch(Exception e){ throw new AuraHandledException('Locations not found'); }
    }
    
    @AuraEnabled
    public static List<Contact> searchContact(String searchTerm) {
        if (searchTerm.length() < 1) {
            return null;
        } else {
            String key = '%' + searchTerm + '%';
            return [SELECT Id, Name, Email, Phone
                    FROM Contact WHERE Name LIKE :key OR Email LIKE :key OR Phone LIKE :key ORDER BY Name LIMIT 10];
        }
    }
}